name: Upload App

on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - run: mkdir artifacts
    # create zip in artifacts folder
    - run: zip -r artifacts/artifact.zip ./lambda
    # use this premade github action for s3 sync
    # https://github.com/jakejarvis/s3-sync-action
    - uses: jakejarvis/s3-sync-action@master
      with:
        args: --follow-symlinks --delete --exclude '.git/*'
      env:
      # aws credentials as set in the project on github
        AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_REGION: 'ca-central-1'
        SOURCE_DIR: './artifacts'
